defmodule Timeclock.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:accounts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :first_name, :text, null: false
      add :middle_name, :text, null: false
      add :last_name, :text, null: false
      add :full_name, :text, null: false
      add :birth_date, :date, null: false
      add :gender, :text, null: false
      add :address, :text, null: false
      add :city, :text, null: false
      add :state, :text, null: false
      add :phone, :text, null: false
      add :mobile, :text, null: false
      add :email, :text, null: false
      add :picture_uri, :text, null: false
      add :custom_id, :text, null: false
      add :custom_field1, :text, null: false
      add :custom_field2, :text, null: false
      add :custom_field3, :text, null: false
      add :custom_field4, :text, null: false
      add :custom_field5, :text, null: false
      add :custom_field6, :text, null: false
      add :custom_field7, :text, null: false
      add :custom_field8, :text, null: false
      add :custom_field9, :text, null: false
      add :custom_field10, :text, null: false
      add :is_time_attendance_user, :boolean, null: false
      add :is_archived, :boolean, null: false
      add :has_user_account, :boolean, null: false
      add :has_assigned_pin, :boolean, null: false
      add :calculation_start_date, :date, null: false
      add :calculation_stop_date, :date, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "accounts_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:accounts, "accounts_user_id_fkey")

    drop table(:accounts)
  end
end
