defmodule Timeclock.Repo.Migrations.AddResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:addresses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :street, :text
      add :city, :text
      add :state, :text
      add :postal_code, :text
      add :country, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_id, :uuid
    end

    create table(:absences, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :start_date, :utc_datetime, null: false
      add :end_date, :utc_datetime, null: false
      add :status, :text, null: false
      add :reason, :text, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :uuid
      add :approved_by_id, :uuid
      add :absence_definition_id, :uuid
    end

    create table(:tasks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text
      add :description, :text
      add :due_date, :utc_datetime

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :assignment_id, :uuid
      add :project_id, :uuid
      add :task_id, :uuid
    end

    create table(:aggregate_functions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :type, :text, null: false
      add :is_enabled, :boolean, default: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:aggregate_functions, [:id], name: "aggregate_functions_unique_id_index")

    create table(:approval_requests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :period_start, :utc_datetime, null: false
      add :period_end, :utc_datetime, null: false
      add :period_options, :map, null: false
      add :status, :text, null: false
      add :is_dirty, :boolean, default: false
      add :additional_data, :map, null: false
      add :is_partial, :boolean, default: false
      add :partial_time_from, :time
      add :partial_time_to, :time
      add :current_approver_names, :map

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :status_set_by_user_id, :uuid
      add :user_id, :uuid
      add :icon_id, :uuid
      add :request_definition_id, :uuid
      add :request_additional_data_id, :uuid
      add :request_log_id, :uuid
    end

    create table(:calculation_details, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text
      add :value, :text
      add :value_type, :text
      add :color, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:calculation_details, [:id], name: "calculation_details_unique_id_index")

    create table(:origins, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text
      add :value, :bigint

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:origins, [:id], name: "origins_unique_id_index")

    create table(:assignments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :start_date, :utc_datetime
      add :end_date, :utc_datetime

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :uuid
      add :project_id, :uuid
      add :role_id, :uuid
    end

    create table(:schedules, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :start_time, :utc_datetime
      add :end_time, :utc_datetime

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :uuid
      add :shift_id, :uuid
    end

    create table(:tags, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text
      add :uri, :text
    end

    create unique_index(:tags, [:id], name: "tags_unique_id_index")

    alter table(:assignments) do
      modify :user_id,
             references(:tags,
               column: :id,
               name: "assignments_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create table(:absence_definitions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :type, :text, null: false
      add :max_days_per_year, :bigint, null: false
      add :fraction, :bigint, null: false
      add :active, :boolean, null: false
      add :available_for_admins_only, :boolean, null: false
      add :description, :text, null: false
      add :requires_approval, :boolean, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :code_id, :uuid
      add :tag_id, :uuid
      add :icon_id, :uuid
    end

    create table(:codes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :code, :text
    end

    create unique_index(:codes, [:code], name: "codes_unique_code_index")

    create unique_index(:codes, [:id], name: "codes_unique_id_index")

    alter table(:absence_definitions) do
      modify :code_id,
             references(:codes,
               column: :id,
               name: "absence_definitions_code_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :tag_id,
             references(:tags,
               column: :id,
               name: "absence_definitions_tag_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :icon_id,
             references(:tags,
               column: :id,
               name: "absence_definitions_icon_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:absence_definitions, [:id], name: "absence_definitions_unique_id_index")

    create table(:shifts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text
      add :start_time, :time
      add :end_time, :time

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:shifts, [:id], name: "shifts_unique_id_index")

    create table(:points, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text
      add :value, :bigint

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:points, [:id], name: "points_unique_id_index")

    create table(:calendar_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text
      add :date, :date
      add :valid_to, :date
      add :recurring_mode, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :group_id, :uuid
      add :event_type_id, :uuid
    end

    create table(:roles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :permissions, {:array, :text}, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :uuid
    end

    create table(:clocking_definition, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text
      add :type, :text
      add :is_active, :boolean, default: true
      add :restriction_type, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :code_id,
          references(:codes,
            column: :id,
            name: "clocking_definition_code_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :starting_category_definition_id, :uuid
      add :absence_category_definition_id, :uuid
      add :in_clocking_definition_id, :uuid
      add :out_clocking_definition_id, :uuid
      add :tag_id, :uuid
    end

    create table(:geolocations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :latitude, :float
      add :longitude, :float
      add :recorded_at, :utc_datetime

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:geolocations, [:id], name: "geolocations_unique_id_index")

    create table(:adjustment_definitions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :type, :text, null: false
      add :is_available_for_admins_only, :boolean, default: false
      add :is_active, :boolean, default: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :account_id, :uuid
      add :code_id, :uuid
      add :tags_id, :uuid
      add :caculation_result_id, :uuid
    end

    create table(:organizations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:organizations, [:id], name: "organizations_unique_id_index")

    create table(:calculation_categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text
      add :color, :text
      add :value, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:calculation_categories, [:id],
             name: "calculation_categories_unique_id_index"
           )

    create table(:cards, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :brand, :text
      add :exp_month, :bigint
      add :exp_year, :bigint
      add :last4, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:cards, [:id], name: "cards_unique_id_index")

    create table(:clocking_interface_details, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :button_index, :bigint
      add :event_index, :bigint
      add :is_default, :boolean, default: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :definition_id,
          references(:clocking_definition,
            column: :id,
            name: "clocking_interface_details_definition_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :icon_id,
          references(:tags,
            column: :id,
            name: "clocking_interface_details_icon_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :tag_id,
          references(:tags,
            column: :id,
            name: "clocking_interface_details_tag_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:clocking_interface_details, [:id],
             name: "clocking_interface_details_unique_id_index"
           )

    create table(:break_rules, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text
      add :duration_minutes, :bigint
      add :applies_after_hours, :bigint

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:break_rules, [:id], name: "break_rules_unique_id_index")

    create table(:audit_log_types, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :display_name, :text
      add :value, :bigint

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:audit_log_types, [:id], name: "audit_log_types_unique_id_index")

    create table(:request_types, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :request_type, :bigint
    end

    create unique_index(:request_types, [:id], name: "request_types_unique_id_index")

    create table(:category_definitions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text
      add :presence_status, :text
      add :paid_time_status, :text
      add :color, :text
      add :code, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :icon_id,
          references(:tags,
            column: :id,
            name: "category_definitions_icon_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:category_definitions, [:code],
             name: "category_definitions_unique_code_index"
           )

    create unique_index(:category_definitions, [:id],
             name: "category_definitions_unique_id_index"
           )

    alter table(:clocking_definition) do
      modify :starting_category_definition_id,
             references(:category_definitions,
               column: :id,
               name: "clocking_definition_starting_category_definition_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :absence_category_definition_id,
             references(:category_definitions,
               column: :id,
               name: "clocking_definition_absence_category_definition_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :in_clocking_definition_id,
             references(:clocking_definition,
               column: :id,
               name: "clocking_definition_in_clocking_definition_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :out_clocking_definition_id,
             references(:clocking_definition,
               column: :id,
               name: "clocking_definition_out_clocking_definition_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :tag_id,
             references(:tags,
               column: :id,
               name: "clocking_definition_tag_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:clocking_definition, [:id], name: "clocking_definition_unique_id_index")

    create table(:clockings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :timestamp, :utc_datetime
      add :original_timestamp, :utc_datetime
      add :is_authentic, :boolean, default: false
      add :comment, :text
      add :status, :text
      add :geo_location_timestamp, :utc_datetime
      add :has_geo_location, :boolean, default: false
      add :accuracy, :float

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :uuid
      add :modified_by_user_id, :uuid
      add :device_id, :uuid
      add :beacon_id, :uuid
      add :point_id, :uuid
      add :definition_id, :uuid
      add :interface_detail_id, :uuid
      add :origin_id, :uuid
      add :original_clocking_definition_id, :uuid
      add :approval_request_id, :uuid
    end

    create table(:departments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :starting_category_definition_id,
          references(:category_definitions,
            column: :id,
            name: "departments_starting_category_definition_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :absence_category_definition_id,
          references(:category_definitions,
            column: :id,
            name: "departments_absence_category_definition_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :in_clocking_definition_id,
          references(:clocking_definition,
            column: :id,
            name: "departments_in_clocking_definition_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :out_clocking_definition_id,
          references(:clocking_definition,
            column: :id,
            name: "departments_out_clocking_definition_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :company_id, :uuid
    end

    create table(:approval_permission_delegations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :delegated_user_id, :uuid
      add :user_id, :uuid
    end

    create table(:approval_request_definitions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text
      add :request_type, :bigint
      add :start_time_parameter_required, :boolean, default: false
      add :end_time_parameter_required, :boolean, default: false
      add :numeric_value_required, :boolean, default: false
      add :time_value_required, :boolean, default: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:approval_request_definitions, [:id],
             name: "approval_request_definitions_unique_id_index"
           )

    create table(:employees, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :position, :text, null: false
      add :hired_at, :text, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :uuid
      add :department_id, :uuid
    end

    create table(:companies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text
      add :registration_number, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "companies_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:companies, [:id], name: "companies_unique_id_index")

    alter table(:addresses) do
      modify :company_id,
             references(:companies,
               column: :id,
               name: "addresses_company_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:addresses, [:id], name: "addresses_unique_id_index")

    alter table(:departments) do
      modify :company_id,
             references(:companies,
               column: :id,
               name: "departments_company_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:departments, [:id], name: "departments_unique_id_index")

    create table(:adjustments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :value, :float, null: false
      add :is_authentic, :boolean, default: false
      add :comment, :text
      add :status, :text
      add :origin, :text
      add :inserted_on, :utc_datetime
      add :partial_time_from, :time
      add :partial_time_to, :time
      add :is_partial, :boolean, default: false
      add :partial_time_duration, :float
      add :approval_request, :map

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :account_id, :uuid
      add :definition_id, :uuid
      add :calculation_result_id, :uuid
      add :icon_id, :uuid
    end

    create table(:managers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :uuid
      add :department_id, :uuid
    end

    create table(:time_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :clock_in, :utc_datetime
      add :clock_out, :utc_datetime
      add :total_hours, :float

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :uuid
      add :task_id, :uuid
    end

    create table(:calculations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :date_from, :date
      add :date_to, :date
      add :users_count, :bigint
      add :users_calculations, :map
      add :calculation_details_summaries, :map
      add :plan_sum_value, :decimal
      add :difference_sum_value, :decimal
      add :paid_presence_sum_value, :decimal
      add :paid_all_day_absence_sum_value, :decimal
      add :missing_presence_sum_value, :decimal
      add :unpaid_presence_sum_value, :decimal
      add :work_free_days_sum_value, :decimal
      add :work_days_sum_value, :decimal
      add :is_calculation_valid, :boolean, default: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:calculations, [:id], name: "calculations_unique_id_index")

    create table(:approval_request_additional_data, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :integer_value, :text
      add :time_value, :time
      add :appliers_comment, :text
      add :approvers_comment, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:approval_request_additional_data, [:id],
             name: "approval_request_additional_data_unique_id_index"
           )

    create table(:projects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text
      add :start_date, :utc_datetime
      add :end_date, :utc_datetime

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "projects_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:projects, [:id], name: "projects_unique_id_index")

    alter table(:assignments) do
      modify :project_id,
             references(:projects,
               column: :id,
               name: "assignments_project_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create table(:calendars, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text
      add :timezone, :text
      add :work_days, {:array, :text}

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:calendars, [:id], name: "calendars_unique_id_index")

    create table(:calendar_event_types, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :display_name, :text
      add :value, :bigint

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:calendar_event_types, [:id],
             name: "calendar_event_types_unique_id_index"
           )

    create table(:beacons, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text
      add :value, :bigint

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:beacons, [:id], name: "beacons_unique_id_index")

    create table(:audit_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :table_name, :text
      add :ip_address, :text
      add :action, :text
      add :date_time, :utc_datetime
      add :old_value, :map
      add :new_value, :map

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :account_id, :uuid
      add :user_id, :uuid
      add :log_type_id, :uuid
    end

    create table(:approval_request_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :action, :text
      add :date_time, :utc_datetime

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :uuid
    end

    create table(:calendar_groups, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text
      add :workdays, :map
      add :time_zone, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:calendar_groups, [:id], name: "calendar_groups_unique_id_index")

    alter table(:calendar_events) do
      modify :group_id,
             references(:calendar_groups,
               column: :id,
               name: "calendar_events_group_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :event_type_id,
             references(:calendar_event_types,
               column: :id,
               name: "calendar_events_event_type_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:calendar_events, [:id], name: "calendar_events_unique_id_index")

    alter table(:absences) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "absences_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :approved_by_id,
             references(:users,
               column: :id,
               name: "absences_approved_by_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :absence_definition_id,
             references(:absence_definitions,
               column: :id,
               name: "absences_absence_definition_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:absences, [:id], name: "absences_unique_id_index")

    alter table(:approval_requests) do
      modify :status_set_by_user_id,
             references(:users,
               column: :id,
               name: "approval_requests_status_set_by_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "approval_requests_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :icon_id,
             references(:tags,
               column: :id,
               name: "approval_requests_icon_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :request_definition_id,
             references(:approval_request_definitions,
               column: :id,
               name: "approval_requests_request_definition_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :request_additional_data_id,
             references(:approval_request_additional_data,
               column: :id,
               name: "approval_requests_request_additional_data_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:schedules) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "schedules_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :shift_id,
             references(:shifts,
               column: :id,
               name: "schedules_shift_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:schedules, [:id], name: "schedules_unique_id_index")

    alter table(:roles) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "roles_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:roles, [:id], name: "roles_unique_id_index")

    alter table(:assignments) do
      modify :role_id,
             references(:roles,
               column: :id,
               name: "assignments_role_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:assignments, [:id], name: "assignments_unique_id_index")

    alter table(:tasks) do
      modify :assignment_id,
             references(:assignments,
               column: :id,
               name: "tasks_assignment_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :project_id,
             references(:projects,
               column: :id,
               name: "tasks_project_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :task_id,
             references(:tasks,
               column: :id,
               name: "tasks_task_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:tasks, [:id], name: "tasks_unique_id_index")

    alter table(:clockings) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "clockings_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :modified_by_user_id,
             references(:users,
               column: :id,
               name: "clockings_modified_by_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:approval_permission_delegations) do
      modify :delegated_user_id,
             references(:users,
               column: :id,
               name: "approval_permission_delegations_delegated_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "approval_permission_delegations_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:approval_permission_delegations, [:id],
             name: "approval_permission_delegations_unique_id_index"
           )

    alter table(:employees) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "employees_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :department_id,
             references(:departments,
               column: :id,
               name: "employees_department_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:employees, [:id], name: "employees_unique_id_index")

    alter table(:managers) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "managers_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :department_id,
             references(:departments,
               column: :id,
               name: "managers_department_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:managers, [:id], name: "managers_unique_id_index")

    alter table(:time_entries) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "time_entries_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :task_id,
             references(:tasks,
               column: :id,
               name: "time_entries_task_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:time_entries, [:id], name: "time_entries_unique_id_index")

    alter table(:approval_request_logs) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "approval_request_logs_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:approval_request_logs, [:id],
             name: "approval_request_logs_unique_id_index"
           )

    alter table(:approval_requests) do
      modify :request_log_id,
             references(:approval_request_logs,
               column: :id,
               name: "approval_requests_request_log_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:approval_requests, [:id], name: "approval_requests_unique_id_index")

    alter table(:users) do
      add :user_name, :citext, null: false
      add :status, :citext, null: false
    end

    create table(:analytics_activities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :properties, :map, default: %{}

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:analytics_activities, [:id],
             name: "analytics_activities_unique_id_index"
           )

    create table(:accounts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:adjustment_definitions) do
      modify :account_id,
             references(:accounts,
               column: :id,
               name: "adjustment_definitions_account_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :code_id,
             references(:codes,
               column: :id,
               name: "adjustment_definitions_code_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :tags_id,
             references(:tags,
               column: :id,
               name: "adjustment_definitions_tags_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :caculation_result_id,
             references(:calculation_details,
               column: :id,
               name: "adjustment_definitions_caculation_result_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:adjustment_definitions, [:id],
             name: "adjustment_definitions_unique_id_index"
           )

    alter table(:adjustments) do
      modify :account_id,
             references(:accounts,
               column: :id,
               name: "adjustments_account_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :definition_id,
             references(:adjustment_definitions,
               column: :id,
               name: "adjustments_definition_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :calculation_result_id,
             references(:calculation_details,
               column: :id,
               name: "adjustments_calculation_result_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :icon_id,
             references(:tags,
               column: :id,
               name: "adjustments_icon_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:adjustments, [:id], name: "adjustments_unique_id_index")

    alter table(:audit_logs) do
      modify :account_id,
             references(:accounts,
               column: :id,
               name: "audit_logs_account_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "audit_logs_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :log_type_id,
             references(:audit_log_types,
               column: :id,
               name: "audit_logs_log_type_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:audit_logs, [:id], name: "audit_logs_unique_id_index")

    alter table(:accounts) do
      add :first_name, :text, null: false
      add :middle_name, :text, null: false
      add :last_name, :text, null: false
      add :birth_date, :date, null: false
      add :gender, :text, null: false
      add :address, :text, null: false
      add :city, :text, null: false
      add :state, :text, null: false
      add :phone, :text, null: false
      add :mobile, :text, null: false
      add :email, :text, null: false
      add :picture_uri, :text, null: false
      add :custom_id, :text, null: false
      add :custom_field1, :text, null: false
      add :custom_field2, :text, null: false
      add :custom_field3, :text, null: false
      add :custom_field4, :text, null: false
      add :custom_field5, :text, null: false
      add :custom_field6, :text, null: false
      add :custom_field7, :text, null: false
      add :custom_field8, :text, null: false
      add :custom_field9, :text, null: false
      add :custom_field10, :text, null: false
      add :is_time_attendance_user, :boolean, null: false
      add :is_archived, :boolean, null: false
      add :assigned_pin, :bigint, null: false
      add :calculation_start_date, :date, null: false
      add :calculation_stop_date, :date, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "accounts_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:devices, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text
      add :value, :bigint

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:devices, [:id], name: "devices_unique_id_index")

    alter table(:clockings) do
      modify :device_id,
             references(:devices,
               column: :id,
               name: "clockings_device_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :beacon_id,
             references(:beacons,
               column: :id,
               name: "clockings_beacon_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :point_id,
             references(:points,
               column: :id,
               name: "clockings_point_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :definition_id,
             references(:clocking_definition,
               column: :id,
               name: "clockings_definition_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :interface_detail_id,
             references(:clocking_interface_details,
               column: :id,
               name: "clockings_interface_detail_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :origin_id,
             references(:origins,
               column: :id,
               name: "clockings_origin_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :original_clocking_definition_id,
             references(:clocking_definition,
               column: :id,
               name: "clockings_original_clocking_definition_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :approval_request_id,
             references(:approval_requests,
               column: :id,
               name: "clockings_approval_request_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:clockings, [:id], name: "clockings_unique_id_index")
  end

  def down do
    drop_if_exists unique_index(:clockings, [:id], name: "clockings_unique_id_index")

    drop constraint(:clockings, "clockings_device_id_fkey")

    drop constraint(:clockings, "clockings_beacon_id_fkey")

    drop constraint(:clockings, "clockings_point_id_fkey")

    drop constraint(:clockings, "clockings_definition_id_fkey")

    drop constraint(:clockings, "clockings_interface_detail_id_fkey")

    drop constraint(:clockings, "clockings_origin_id_fkey")

    drop constraint(:clockings, "clockings_original_clocking_definition_id_fkey")

    drop constraint(:clockings, "clockings_approval_request_id_fkey")

    alter table(:clockings) do
      modify :approval_request_id, :uuid
      modify :original_clocking_definition_id, :uuid
      modify :origin_id, :uuid
      modify :interface_detail_id, :uuid
      modify :definition_id, :uuid
      modify :point_id, :uuid
      modify :beacon_id, :uuid
      modify :device_id, :uuid
    end

    drop_if_exists unique_index(:devices, [:id], name: "devices_unique_id_index")

    drop table(:devices)

    drop constraint(:accounts, "accounts_user_id_fkey")

    alter table(:accounts) do
      remove :user_id
      remove :updated_at
      remove :created_at
      remove :calculation_stop_date
      remove :calculation_start_date
      remove :assigned_pin
      remove :is_archived
      remove :is_time_attendance_user
      remove :custom_field10
      remove :custom_field9
      remove :custom_field8
      remove :custom_field7
      remove :custom_field6
      remove :custom_field5
      remove :custom_field4
      remove :custom_field3
      remove :custom_field2
      remove :custom_field1
      remove :custom_id
      remove :picture_uri
      remove :email
      remove :mobile
      remove :phone
      remove :state
      remove :city
      remove :address
      remove :gender
      remove :birth_date
      remove :last_name
      remove :middle_name
      remove :first_name
    end

    drop_if_exists unique_index(:audit_logs, [:id], name: "audit_logs_unique_id_index")

    drop constraint(:audit_logs, "audit_logs_account_id_fkey")

    drop constraint(:audit_logs, "audit_logs_user_id_fkey")

    drop constraint(:audit_logs, "audit_logs_log_type_id_fkey")

    alter table(:audit_logs) do
      modify :log_type_id, :uuid
      modify :user_id, :uuid
      modify :account_id, :uuid
    end

    drop_if_exists unique_index(:adjustments, [:id], name: "adjustments_unique_id_index")

    drop constraint(:adjustments, "adjustments_account_id_fkey")

    drop constraint(:adjustments, "adjustments_definition_id_fkey")

    drop constraint(:adjustments, "adjustments_calculation_result_id_fkey")

    drop constraint(:adjustments, "adjustments_icon_id_fkey")

    alter table(:adjustments) do
      modify :icon_id, :uuid
      modify :calculation_result_id, :uuid
      modify :definition_id, :uuid
      modify :account_id, :uuid
    end

    drop_if_exists unique_index(:adjustment_definitions, [:id],
                     name: "adjustment_definitions_unique_id_index"
                   )

    drop constraint(:adjustment_definitions, "adjustment_definitions_account_id_fkey")

    drop constraint(:adjustment_definitions, "adjustment_definitions_code_id_fkey")

    drop constraint(:adjustment_definitions, "adjustment_definitions_tags_id_fkey")

    drop constraint(:adjustment_definitions, "adjustment_definitions_caculation_result_id_fkey")

    alter table(:adjustment_definitions) do
      modify :caculation_result_id, :uuid
      modify :tags_id, :uuid
      modify :code_id, :uuid
      modify :account_id, :uuid
    end

    drop table(:accounts)

    drop_if_exists unique_index(:analytics_activities, [:id],
                     name: "analytics_activities_unique_id_index"
                   )

    drop table(:analytics_activities)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    alter table(:users) do
      remove :status
      remove :user_name
      remove :email
    end

    drop_if_exists unique_index(:approval_requests, [:id],
                     name: "approval_requests_unique_id_index"
                   )

    drop constraint(:approval_requests, "approval_requests_request_log_id_fkey")

    alter table(:approval_requests) do
      modify :request_log_id, :uuid
    end

    drop_if_exists unique_index(:approval_request_logs, [:id],
                     name: "approval_request_logs_unique_id_index"
                   )

    drop constraint(:approval_request_logs, "approval_request_logs_user_id_fkey")

    alter table(:approval_request_logs) do
      modify :user_id, :uuid
    end

    drop_if_exists unique_index(:time_entries, [:id], name: "time_entries_unique_id_index")

    drop constraint(:time_entries, "time_entries_user_id_fkey")

    drop constraint(:time_entries, "time_entries_task_id_fkey")

    alter table(:time_entries) do
      modify :task_id, :uuid
      modify :user_id, :uuid
    end

    drop_if_exists unique_index(:managers, [:id], name: "managers_unique_id_index")

    drop constraint(:managers, "managers_user_id_fkey")

    drop constraint(:managers, "managers_department_id_fkey")

    alter table(:managers) do
      modify :department_id, :uuid
      modify :user_id, :uuid
    end

    drop_if_exists unique_index(:employees, [:id], name: "employees_unique_id_index")

    drop constraint(:employees, "employees_user_id_fkey")

    drop constraint(:employees, "employees_department_id_fkey")

    alter table(:employees) do
      modify :department_id, :uuid
      modify :user_id, :uuid
    end

    drop_if_exists unique_index(:approval_permission_delegations, [:id],
                     name: "approval_permission_delegations_unique_id_index"
                   )

    drop constraint(
           :approval_permission_delegations,
           "approval_permission_delegations_delegated_user_id_fkey"
         )

    drop constraint(
           :approval_permission_delegations,
           "approval_permission_delegations_user_id_fkey"
         )

    alter table(:approval_permission_delegations) do
      modify :user_id, :uuid
      modify :delegated_user_id, :uuid
    end

    drop constraint(:clockings, "clockings_user_id_fkey")

    drop constraint(:clockings, "clockings_modified_by_user_id_fkey")

    alter table(:clockings) do
      modify :modified_by_user_id, :uuid
      modify :user_id, :uuid
    end

    drop_if_exists unique_index(:tasks, [:id], name: "tasks_unique_id_index")

    drop constraint(:tasks, "tasks_assignment_id_fkey")

    drop constraint(:tasks, "tasks_project_id_fkey")

    drop constraint(:tasks, "tasks_task_id_fkey")

    alter table(:tasks) do
      modify :task_id, :uuid
      modify :project_id, :uuid
      modify :assignment_id, :uuid
    end

    drop_if_exists unique_index(:assignments, [:id], name: "assignments_unique_id_index")

    drop constraint(:assignments, "assignments_role_id_fkey")

    alter table(:assignments) do
      modify :role_id, :uuid
    end

    drop_if_exists unique_index(:roles, [:id], name: "roles_unique_id_index")

    drop constraint(:roles, "roles_user_id_fkey")

    alter table(:roles) do
      modify :user_id, :uuid
    end

    drop_if_exists unique_index(:schedules, [:id], name: "schedules_unique_id_index")

    drop constraint(:schedules, "schedules_user_id_fkey")

    drop constraint(:schedules, "schedules_shift_id_fkey")

    alter table(:schedules) do
      modify :shift_id, :uuid
      modify :user_id, :uuid
    end

    drop constraint(:approval_requests, "approval_requests_status_set_by_user_id_fkey")

    drop constraint(:approval_requests, "approval_requests_user_id_fkey")

    drop constraint(:approval_requests, "approval_requests_icon_id_fkey")

    drop constraint(:approval_requests, "approval_requests_request_definition_id_fkey")

    drop constraint(:approval_requests, "approval_requests_request_additional_data_id_fkey")

    alter table(:approval_requests) do
      modify :request_additional_data_id, :uuid
      modify :request_definition_id, :uuid
      modify :icon_id, :uuid
      modify :user_id, :uuid
      modify :status_set_by_user_id, :uuid
    end

    drop_if_exists unique_index(:absences, [:id], name: "absences_unique_id_index")

    drop constraint(:absences, "absences_user_id_fkey")

    drop constraint(:absences, "absences_approved_by_id_fkey")

    drop constraint(:absences, "absences_absence_definition_id_fkey")

    alter table(:absences) do
      modify :absence_definition_id, :uuid
      modify :approved_by_id, :uuid
      modify :user_id, :uuid
    end

    drop table(:users)

    drop_if_exists unique_index(:calendar_events, [:id], name: "calendar_events_unique_id_index")

    drop constraint(:calendar_events, "calendar_events_group_id_fkey")

    drop constraint(:calendar_events, "calendar_events_event_type_id_fkey")

    alter table(:calendar_events) do
      modify :event_type_id, :uuid
      modify :group_id, :uuid
    end

    drop_if_exists unique_index(:calendar_groups, [:id], name: "calendar_groups_unique_id_index")

    drop table(:calendar_groups)

    drop table(:approval_request_logs)

    drop table(:audit_logs)

    drop_if_exists unique_index(:beacons, [:id], name: "beacons_unique_id_index")

    drop table(:beacons)

    drop_if_exists unique_index(:calendar_event_types, [:id],
                     name: "calendar_event_types_unique_id_index"
                   )

    drop table(:calendar_event_types)

    drop_if_exists unique_index(:calendars, [:id], name: "calendars_unique_id_index")

    drop table(:calendars)

    drop constraint(:assignments, "assignments_project_id_fkey")

    alter table(:assignments) do
      modify :project_id, :uuid
    end

    drop_if_exists unique_index(:projects, [:id], name: "projects_unique_id_index")

    drop constraint(:projects, "projects_organization_id_fkey")

    drop table(:projects)

    drop_if_exists unique_index(:approval_request_additional_data, [:id],
                     name: "approval_request_additional_data_unique_id_index"
                   )

    drop table(:approval_request_additional_data)

    drop_if_exists unique_index(:calculations, [:id], name: "calculations_unique_id_index")

    drop table(:calculations)

    drop table(:time_entries)

    drop table(:managers)

    drop table(:adjustments)

    drop_if_exists unique_index(:departments, [:id], name: "departments_unique_id_index")

    drop constraint(:departments, "departments_company_id_fkey")

    alter table(:departments) do
      modify :company_id, :uuid
    end

    drop_if_exists unique_index(:addresses, [:id], name: "addresses_unique_id_index")

    drop constraint(:addresses, "addresses_company_id_fkey")

    alter table(:addresses) do
      modify :company_id, :uuid
    end

    drop_if_exists unique_index(:companies, [:id], name: "companies_unique_id_index")

    drop constraint(:companies, "companies_organization_id_fkey")

    drop table(:companies)

    drop table(:employees)

    drop_if_exists unique_index(:approval_request_definitions, [:id],
                     name: "approval_request_definitions_unique_id_index"
                   )

    drop table(:approval_request_definitions)

    drop table(:approval_permission_delegations)

    drop constraint(:departments, "departments_starting_category_definition_id_fkey")

    drop constraint(:departments, "departments_absence_category_definition_id_fkey")

    drop constraint(:departments, "departments_in_clocking_definition_id_fkey")

    drop constraint(:departments, "departments_out_clocking_definition_id_fkey")

    drop table(:departments)

    drop table(:clockings)

    drop_if_exists unique_index(:clocking_definition, [:id],
                     name: "clocking_definition_unique_id_index"
                   )

    drop constraint(
           :clocking_definition,
           "clocking_definition_starting_category_definition_id_fkey"
         )

    drop constraint(
           :clocking_definition,
           "clocking_definition_absence_category_definition_id_fkey"
         )

    drop constraint(:clocking_definition, "clocking_definition_in_clocking_definition_id_fkey")

    drop constraint(:clocking_definition, "clocking_definition_out_clocking_definition_id_fkey")

    drop constraint(:clocking_definition, "clocking_definition_tag_id_fkey")

    alter table(:clocking_definition) do
      modify :tag_id, :uuid
      modify :out_clocking_definition_id, :uuid
      modify :in_clocking_definition_id, :uuid
      modify :absence_category_definition_id, :uuid
      modify :starting_category_definition_id, :uuid
    end

    drop_if_exists unique_index(:category_definitions, [:id],
                     name: "category_definitions_unique_id_index"
                   )

    drop_if_exists unique_index(:category_definitions, [:code],
                     name: "category_definitions_unique_code_index"
                   )

    drop constraint(:category_definitions, "category_definitions_icon_id_fkey")

    drop table(:category_definitions)

    drop_if_exists unique_index(:request_types, [:id], name: "request_types_unique_id_index")

    drop table(:request_types)

    drop_if_exists unique_index(:audit_log_types, [:id], name: "audit_log_types_unique_id_index")

    drop table(:audit_log_types)

    drop_if_exists unique_index(:break_rules, [:id], name: "break_rules_unique_id_index")

    drop table(:break_rules)

    drop_if_exists unique_index(:clocking_interface_details, [:id],
                     name: "clocking_interface_details_unique_id_index"
                   )

    drop constraint(:clocking_interface_details, "clocking_interface_details_definition_id_fkey")

    drop constraint(:clocking_interface_details, "clocking_interface_details_icon_id_fkey")

    drop constraint(:clocking_interface_details, "clocking_interface_details_tag_id_fkey")

    drop table(:clocking_interface_details)

    drop_if_exists unique_index(:cards, [:id], name: "cards_unique_id_index")

    drop table(:cards)

    drop_if_exists unique_index(:calculation_categories, [:id],
                     name: "calculation_categories_unique_id_index"
                   )

    drop table(:calculation_categories)

    drop_if_exists unique_index(:organizations, [:id], name: "organizations_unique_id_index")

    drop table(:organizations)

    drop table(:adjustment_definitions)

    drop_if_exists unique_index(:geolocations, [:id], name: "geolocations_unique_id_index")

    drop table(:geolocations)

    drop constraint(:clocking_definition, "clocking_definition_code_id_fkey")

    drop table(:clocking_definition)

    drop table(:roles)

    drop table(:calendar_events)

    drop_if_exists unique_index(:points, [:id], name: "points_unique_id_index")

    drop table(:points)

    drop_if_exists unique_index(:shifts, [:id], name: "shifts_unique_id_index")

    drop table(:shifts)

    drop_if_exists unique_index(:absence_definitions, [:id],
                     name: "absence_definitions_unique_id_index"
                   )

    drop constraint(:absence_definitions, "absence_definitions_code_id_fkey")

    drop constraint(:absence_definitions, "absence_definitions_tag_id_fkey")

    drop constraint(:absence_definitions, "absence_definitions_icon_id_fkey")

    alter table(:absence_definitions) do
      modify :icon_id, :uuid
      modify :tag_id, :uuid
      modify :code_id, :uuid
    end

    drop_if_exists unique_index(:codes, [:id], name: "codes_unique_id_index")

    drop_if_exists unique_index(:codes, [:code], name: "codes_unique_code_index")

    drop table(:codes)

    drop table(:absence_definitions)

    drop constraint(:assignments, "assignments_user_id_fkey")

    alter table(:assignments) do
      modify :user_id, :uuid
    end

    drop_if_exists unique_index(:tags, [:id], name: "tags_unique_id_index")

    drop table(:tags)

    drop table(:schedules)

    drop table(:assignments)

    drop table(:tokens)

    drop_if_exists unique_index(:origins, [:id], name: "origins_unique_id_index")

    drop table(:origins)

    drop_if_exists unique_index(:calculation_details, [:id],
                     name: "calculation_details_unique_id_index"
                   )

    drop table(:calculation_details)

    drop table(:approval_requests)

    drop_if_exists unique_index(:aggregate_functions, [:id],
                     name: "aggregate_functions_unique_id_index"
                   )

    drop table(:aggregate_functions)

    drop table(:tasks)

    drop table(:absences)

    drop table(:addresses)
  end
end
